applications.yaml

A few app fixes I applied that I think are "objective" enough to submit upstream.
Formatted properly with format-app-specific-configuration.

Additional Application Fixes

---

applications.yaml

I found that the entire MS Office Suite needs this workaround.

Add app rules for rest of MS Office Suite

---

applications.yaml

adds the following apps:
- discord ptb
- discord canary
- discord development
- logi bolt
- logi tune
- logitech g hub
- logi options
- mica for everyone
- cron
- flow launcher
- modern flyouts
- sharex
also fixes roundedtb

Add more apps

---

applications.yaml

- Force manage conhost windows
- Float Task Manager
- Float [Process Hacker](https://processhacker.sourceforge.io/)
- [Notion Enhanced](https://notion-enhancer.github.io/)
- [ElectronMail](https://github.com/vladimiry/ElectronMail)
- [RepoZ](https://github.com/awaescher/RepoZ)
- [PowerToys](https://github.com/microsoft/PowerToys)
- [Inno Setup](https://jrsoftware.org/isinfo.php)
- [NohBoard](https://github.com/ThoNohT/NohBoard)
- [ProtonVPN](https://protonvpn.com/)
- [Roblox FPS Unlocker](https://github.com/axstin/rbxfpsunlocker)
- [Telegram](https://telegram.org/)
- [Kotatogram](https://kotatogram.github.io/)
- [Mailspring](https://getmailspring.com/)
- [ONLYOFFICE Editors](https://www.onlyoffice.com/office-suite.aspx)
- [Adobe Creative Cloud](https://www.adobe.com/creativecloud.html)
- …

Additional app rules

---

applications.yaml

feat(apps): add msiexec

---

applications.yaml

NVIDIA GeForce Experience is border overflow

feat(apps): add nvidia geforce experience

---

applications.yaml

[WingetUI](https://github.com/martinet101/WingetUI)

feat(apps): add WingetUI

---

applications.yaml

https://github.com/ArmCord/ArmCord

feat(apps): add ArmCord

---

applications.yaml

- [WebTorrent Desktop](https://webtorrent.io/desktop)
- [Houdoku](https://github.com/xgi/houdoku)

feat(apps): add WebTorrent Desktop and Houdoku

---

applications.yaml

- [VRCX](https://github.com/vrcx-team/VRCX) - tray app
- [Ableton Live](https://www.ableton.com/en/live/) - VST2/3 plugin windows should float, not tile

feat(apps): add VRCX and Ableton Live

---

applications.yaml

- prevents the ghost window when nzxt cam.exe opens

feat(apps): add NZXT CAM

---

applications.yaml

Add Akiflow.exe  to tray_and_overflow.
Tested and works well!

Add Akiflow to tray_and_overflow

---

applications.yaml

- [✅] I have formatted `applications.yaml` with `komorebic fmt-asc`.
This PR adds support for handling Unity Hub minimizing to tray.  (identified by exe)

added support for Unity Hub minimizing to tray

---

applications.yaml

Adds `object_name_change` configuration for `Android Studio` so that komorebic can manage it by default.

feat(apps): Android Studio

---

applications.yaml

add border overflow fix for VSCode Insiders

---

applications.yaml

feat(apps): add Affinity Photo 2

---

applications.yaml

Added tray management for Playnite game launcher

feat(apps): add Playnite

---

applications.yaml

feat(apps): add Clementine

---

applications.yaml

`object_name_change` to manage fullscreen mpv using `mpv --fs`.
Closes #38

feat(apps): add mpv

---

applications.yaml

- AutoHotkeyUX
- [Clash Verge](https://github.com/zzzgydi/clash-verge)
- [CopyQ](https://hluk.github.io/CopyQ/)
- [Everything](https://www.voidtools.com/)
- [Golden Dict](http://goldendict.org/)
- ~[ManicTime](https://www.manictime.com/)~
- [OneQuick](https://onequick.org/)
- QQ
- [Sandboxie Plus](https://sandboxie-plus.com/)
- [NetEase Cloud Music](https://music.163.com/)
---

feat(apps): bunch of new apps

---

applications.yaml

Added config for Everything1.5a (Alpha version of Everything) 
Added config for Honeyview (image viewer)

feat(apps): add Everything1.5a & Honeyview

---

applications.yaml

feat(apps): add ProtonDrive

---

applications.yaml

feat(apps): add Brave browser

---

applications.yaml

feat(apps) Rider popup window float indentifier

---

applications.yaml

feat(apps): add Blitz

---

applications.yaml

feat(apps): add FFMetrics

---

applications.yaml

feat(apps): add KOOK

---

applications.yaml

Set SnippingTool as a floating window

feat(apps): add Snipping Tool

---

applications.yaml

fix(unity-hub): add border overflow

---

applications.yaml

feat(apps): add Eagle

---

applications.yaml

add entry for files-community/Files

---

applications.yaml

feat(ea-desktop): add border overflow for EA Desktop Client

---

applications.yaml

Added support for VMware Horizon Client application

feat(apps): add VMWare Horizon Client

---

applications.yaml

I've used [WinLister](https://www.nirsoft.net/utils/winlister.html) to find the class of the windows

feat: add Microsoft Active Accessibility (MSAA)

---

applications.yaml

feat(apps): add PowerToys CropAndLock

---

applications.yaml

Fixed merge conflicts and added border overflow rule for GitHub Desktop.

feat(apps): add GitHub Desktop

---

applications.yaml

feat(apps): add Morgen

---

applications.yaml

feat(apps): add Github Credential Manager

---

applications.yaml

I added a rule for MuseScore that would overflow it's borders.

feat(apps): add MuseScore

---

applications.yaml

I added a float identifier for the PowertAccent popup.

feat(apps/powertoys): Add float identifier for PowerAccent popup

---

applications.yaml

feat(apps): Microsoft SQL Server Management Studio

---

applications.yaml

feat(apps): add Total Commander

---

applications.yaml

feat(apps): add CLion and WebStorm

---

applications.yaml

feat(apps): border overflow for Postman rest client

---

applications.yaml

feat(applications): update format for komorebi v0.1.23

---

applications.yaml

I have just made a small correction.
This is my first pull request so I hope I haven't messed something up.
Thanks

Guitar rig 7 had an incorrect name

---

applications.yaml

feat(apps): add PhpStorm

---

applications.yaml

feat(apps): add affinity suite applications

---

applications.yaml

Hi, added settings for `JetBrains DataGrip x64`.
THX, for your work.

feat(applications): jetbrains datagrip

---

applications.yaml

fix(apps): update Zebar process identifier

---

.gitignore
applications.json

@LGUG2Z @alex-ds13 After some testing, I decided on these changes to the rules based on the conversation in #115 
I moved some rules to be in `floating` and added a new `ignore` rule.

revised rules for Microsoft Visual Studio Community 2022

---

applications.json

Add TeraCopy

---

applications.json

Adding a rule for Line, which is an app and service for instant messaging
https://en.wikipedia.org/wiki/Line_(software)

adding rules for LINE

---

applications.json

Add some basic rules for floating windows in GIMP

Add floating rules for GIMP

---

applications.json

Add manage rule for Tabby

---

applications.json

fixes https://github.com/LGUG2Z/komorebi-application-specific-configuration/issues/144

feat(apps): add microsoft word tray rule

---

applications.json

Adds the JetBrains Client (which is used for remote development with any jetbrains ide)
https://github.com/LGUG2Z/komorebi/pull/1215

Add JetBrains Client

---

applications.json

feat(apps): add ea desktop app

---

applications.json

Add some basic rules for floating windows in `LibreCAD.exe`

Add floating rules for LibreCAD

---

applications.json

feat(apps): add notion calendar

---

applications.json

Add Stremio Desktop Community

---

applications.json

add FreeCAD floating popups support

---

applications.json

See https://github.com/LGUG2Z/komorebi/issues/1300 for more context and insight into the matchers used. Tested to be working with [TuxGuitar](https://github.com/helge17/tuxguitar) (SWT) and [MCA Selector](https://github.com/Querz/mcaselector) (JavaFX).

Add object_name_change rule for all JavaFX/SWT applications

---

applications.json

Implements https://github.com/LGUG2Z/komorebi-application-specific-configuration/issues/179

feat(apps): Add floating rule for MS SQL Server Management Studio

---

applications.json

added powertoys advanced paste ignore list.

ignored powertoys advanced paste

---

applications.json

feat(apps): Add ignore rule for PowerToys Command Palette

---

applications.json

Add support for TablePlus DB Gui via applications.json
[TablePlus](https://tableplus.com/)

Add rules pretaining to TablePlus DB GUI

---

applications.json

Add ignore rule for Browser Tamer

---

applications.json

A more strict rule so it does not conflict with other apps

fix(apps): Microsoft SQL Server Management Studio composite rule
