LGUG2Z/komorebi-application-specific-configuration

applications.yaml
Adds a float rule for windows with class `MozillaTaskbarPreviewClass`.  These invisible windows are spawned by Firefox when its "Show tab previews in the Windows taskbar" option is enabled, presumably as a way to populate thumbnails for inactive tabs.  Komorebi will then try to tile these and make a mess of the layout.
The setting in question:
=> Ignore hidden windows spawned by Firefox tab previews

applications.yaml
[Wox is a FOSS desktop launcher similar to rofi on linux.](http://www.wox.one/)
I couldn't target window class because the string ends with a random GUID which changes after every app launch, so I targeted the window title. However, the window title is a bit generic which makes me a bit uneasy. I'm curious if targeting a window title that belongs to a process is in the plans?
=> Add hidden window spawned by Wox

applications.yaml
Capitalization thing. `slack.exe` is the bootstrapper, while `Slack.exe` is the actual application.
=> fix(slack): update executable name

applications.yaml
Float the metro-styled dialog from `SystemSettings.exe`:
=> feat(apps): add systemsettings dialog

applications.yaml
paint.net uses multiple windows within the app, which breaks when attempting to tile.
=> feat(apps): Add float rule for paint.net

applications.yaml
WingetUI executable name became lowercase in the latest update
=> chore(wingetui): add additional executable name

.gitignore
Useful when you have `overrides.yaml` in the directory
=> chore: add overrides.yaml to gitignore

applications.yaml
Added entries for WinZip 64-bit and 32-bit exe files to treat them as floating applications.
Note: Since I use komorebi on my work laptop, I couldn't use that to raise this PR due to organization policy and had to use my Mac to raise this PR, which is why I was unable to run the formatter.
=> feat(apps): add WinZip

applications.yaml
Mattermost (an Electron-based chat app, like Discord/Slack) was missing. From my quick testing adding this here resolves it.
=> feat(apps): add Mattermost

applications.yaml
This adds `matching_strategy` to all `identifier` and `float_identifiers` that currently do not explicitly specify it. In each of these cases, the matcher is set to the current Komorebi default values: `Equals` for `Exe`; `Legacy` for `Class` and `Title`. 
This paths the way to a future enforcing of an explicit matcher for each rule. Moreover, by making all implicit uses of `Legacy` explicit, this PR enables future PRs that scrutinize each `Legacy` rule, replacing them with a more appropriate choice of `Equals`, `StartsWith` or `EndsWith`. In that, it helps moving towards an eventual depreciation of `Legacy` as the default.
=> Explicitly set `matching_strategies` if unspecified

.gitignore, applications.yaml
[Viture](https://www.viture.com/) have today released [SpaceWalker](https://academy.viture.com/xr_glasses/spacewalker_windows) for windows, which allows the glasses to use 3 virtual displays. 
Unfortunately, they implement the 3 degrees of freedom 3-virtual-display mode as a window in a fourth monitor, which gets managed by komorebi which causes them to get wedged.  
This seems to fix that problem.
=> Viture Spacewalker app

applications.yaml
* For Amazon Chime: only ignore the Meeting Control pop-up, which is activated during an active call, when the user shifts the focused window to anything that's not that Amazon Chime meeting window. This pop-up needs to be ignored.
* For Core Temp: the GUI does not scale, thus should be ignored by komorebi (or kept as a floating window).
=> add float_rule for Amazon Chime and Core Temp

applications.yaml
Added programs known by their executable "acad.exe".
Tested by personal use in:
- Autodesk AutoCAD
- Autodesk Civil3D
=> feat(applications): add AutoCAD and derivatives

applications.yaml
Added rules for Microsoft Visio to force management of the main application window (class `VISIOA`) and float/unmanage the windows within the main application window (this includes Document windows with class `VISIOA` and ShapeSheet Editor windows with class `VISIOQ`)
Please be aware that this has only been tested on the version of Visio bundled with Office 365 subscription. Older versions (2007/2010/2013/etc) might behave differently. Unfortunately I'm not sure any of those versions can be tested without a licensed install.  However, I'd speculate that the rules might work on those versions as well, given that the UI hasn't changed from a qualitative standpoint, and hasn't been rigorously overhauled like Microsoft's other Office 365 apps. If anyone out there is working on an older …
=> Added rules for Microsoft Visio

applications.json
Hello again!
Here is the PR that makes Unity Editor ignore transparency. 
When testing this I realized I'm still on Komorebi 1.29 so I had to upgrade to 1.30. This then had me discover an issue with Unity creating a console window that get's minimized to tray when starting which I didn't see in 1.29. (The effect it had was that Komorebi was showing an empty space for a minimized window) 
I took the liberty to add a `tray_and_multi_window` rule to fix that in a separate commit, hopefully that's cool and not making the PR do too many things. 
I tested both on my machine with latest Unity and it seems to be working,
=> Add transparency and multi window rules for Unity Engine

applications.json, applications.yaml
WinGetUI rebranded to UniGetUI, so the old WinGetUI rules no longer apply. This copies the old rules, changing the name.
The old `applications.yaml` has two rules with different capitalization, which I did not include.
^ this causes a big diff with unrelated changes (82+ 82-)
=> Add UniGetUI tray rule

.gitignore, applications.json
@LGUG2Z I have expanded on the ignore rules for `Visual Studio`.
I am not 100% sure if the composite rules need to include the match on `Exe`
```json
{
"kind": "Exe",
"id": "devenv.exe",
"matching_strategy": "Equals"
}
```
But let's see what you say 🤔
=> ignore rules for Microsoft Visual Studio Community 2022

applications.json
changing rule to composite due to conflict with Remote Desktop Manager as [requested](https://github.com/LGUG2Z/komorebi-application-specific-configuration/pull/115#discussion_r1831639545)
=> revised rules for Microsoft Visual Studio Community 2022

applications.json
This change is correcting a typo on a composite rule for visual studio
=> typo in composite rule - visual studio

applications.json
As described in #127 , this adds ignore rules for GoLand, in similar fashion to other jetbrains IDEs
=> feat(apps): add goland rules similar to other jetbrains IDEs

applications.json
This might fix some popup window issues like calc and export utility present in acad.exe programs like AutoCAD and Civil3D.
=> Fix some popup window issues with acad.exe

applications.json
LibreOffice apps apparently do not emit `Show` events when starting, only `ObjectNameChange` events. So this config should make them able to be tiled by komorebi.
=> add LibreOffice config

applications.json
@LGUG2Z I'm not sure about those classes for WSL processes... Are you ok with the `WSL default ignores`?
Also why was that `ApplicationFrameHost` hardcoded as `tray_and_multi_window` should that be kept?!
=> fix: add missing hardcoded defaults

applications.json
Support for Official Notion desktop application.
Windows titled `Notion - Command Search` indicate:
- Toggle command search (default: `ctrl+shift+k`)
- Toggle Notion AI (default `ctrl+shift+j`)
=> feat(apps): add notion

applications.json
added a new ignore rule for a `Building font cache` popup window
=> feat(apps): add ignore rule for vlc

applications.json
added ignore rule for the startup splash screen of [Lens](https://k8slens.dev/), which is `a Kubernetes platform that provides tools for seamless interaction with Kubernetes clusters, and an environment for secure and effective work.`
=> feat(apps): add ignore rule for lens (kubernetes platform)

applications.json
Window rule for Mod organizer 2's installation window.
For detailed information and video to demonstrate changes link to issue #165 is below : 
[Add ignore rule Mod Organizer 2 pop-up installation windows](https://github.com/LGUG2Z/komorebi-application-specific-configuration/issues/165)
Application rule is set for
https://github.com/ModOrganizer2/modorganizer
=> Add Mod Organizer 2

applications.json
[Barrier](https://github.com/debauchee/barrier) lets you share a mouse & keyboard between multiple computers. Typically, its windows are not able to be resized. When komorebi force-resizes them, they do *not* scale property, resulting in large amounts of blank space, hidden elements you can no longer see, or multiple elements stacked on top of each other.
Barrier does get minimized to the tray, however, it seemed to be behaving correctly so I didn't add a `tray_and_multi_window` rule. If I should add it anyway, please let me know.
I'm matching the exe name since the class is a generic QT 5 class (`Qt5QWindowIcon`).
=> Add float rule for Barrier

applications.json
[Prime95](https://www.mersenne.org/download/) is a tool often used to stress-test CPU and/or memory. When starting a stress test, it creates N "sub-windows" within its primary window, where N is the number of cores you're testing. These windows do not render outside of the primary window. komorebi will try to create new tiles for all of them, meaning you end up with N ghost tiles and the inability to see the contents of any of the windows.
I'm matching the exe name since each worker's title is different, and the class appears to change every time it's opened.
=> Add float rule for prime95

applications.json
[Desktop Mate](https://store.steampowered.com/app/3301060/Desktop_Mate/) adds characters that interact with your desktop and open windows. It works by using a transparent window. When komorebi manages it, it creates a persistent ghost tile for said window and moves the character back to the center of that ghost for one frame whenever the layout changes or permanently in the case of changing workspaces. I opted to ignore it from komorebi instead of marking it as floating since the point is to have an avatar that's always on screen, so making them disappear when changing workspaces mostly defeats the purpose.
I'm matching the exe name since the class is a generic Unity class (`UnityWndClass`).
=> Add ignore rule for Desktop Mate

applications.json
#169 broke the schema with a capital `K` in the `kind` field, causing komorebi to fail to start when loading it.
Apologies for this. I should've spotted it. It seems like there's a few pre-made GitHub actions for validating JSON schema (e.g. [validate-json](https://github.com/marketplace/actions/validate-json)) which could be helpful to avoid this in the future.
=> Fix schema error in prime95 config

.github/workflows/validate-schema.yaml, applications.json
Adds a GitHub action that runs on PRs and pushes to validate the `applications.json` schema to avoid issues like #169 caused.
Here's example runs with a valid and invalid schema:
Valid Schema: https://github.com/Insprill/komorebi-application-specific-configuration/actions/runs/13300938984
Invalid Schema: https://github.com/Insprill/komorebi-application-specific-configuration/actions/runs/13300944725
This action also has [the option to comment on PRs](https://github.com/GrantBirki/json-yaml-validate?tab=readme-ov-file#pull-request-comment) with schema violations that I left disabled. I can enable it if you'd like.
I had to remove the comment for `Microsoft Terminal Services Client` since it caused a syntax error while parsing.
=> Add GitHub action for validating JSON schema

applications.json
MOTU's [software](https://motu.com/en-us/download/#category=1&product=408) for the M-Series audio interfaces does not scale as the window size changes, and instead leaves a large amount of blank space.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
=> Add float rule for the MOTU M-Series software

applications.json
Adds a float rule for [Clumsy](https://github.com/jagt/clumsy). Clumsy's window normally isn't allowed to be resized. When Clumsy opens, it immediately asks to escalate to admin permissions. Before you accept that, it will take up a tile, which isn't desirable. In that brief time, the window also does not scale, either cutting off contents if it's too small, or ending up with a large amount of white space if it's too large.
=> Add float rule for Clumsy

applications.json
When Steam's update window gets resized by komorebi, it does not dynamically adjust the contents and instead creates a giant pure-white window.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
=> Add float rule for Steam's update window

applications.json
Adds a float rule for GIMP's "About GIMP" window that shows when there's an update or when going to `Help > About GIMP`.
Without this rule, the window contents scale awkwardly at smaller sizes, and it's generally not a window I'd imagine anyone would want to tile.
~~I only included a Title matcher, although I can also match the exe like the other float rule if desired.~~
=> Add float rule for GIMP's "About GIMP" window

applications.json
[Prism Launcher](https://prismlauncher.org/) has several popup windows (general settings, instance settings, account management) all of which have a minimum size that they will *not* scale below. This minimum size is fairly large, so once komorebi tries to tile it with more than three other windows open simultaneously (on my 21:9 monitor) they will start overlapping other applications, or render off-screen.
Other popups also have a maximum size that they will *not* scale above, like the progress dialog when downloading a new version. This will result in a tile with huge margins.
I chose the matcher as anything containing `- Prism Launcher` since the normal Prism Launcher window title is `Prism Launcher 8.3` (`8.3` is the version), and all popup windows have the title `XYZ - Prism Launcher …
=> Add float rule for Prism Launcher's popup windows

applications.json
PR for #163. Took your advice and created a composite rule for ALL `"class": "Ableton Live Window Class"` that don't match "Ableton" in the title. 
This seems to take care of all Ableton-native sub-windows including export settings, export progress bar, AND the settings window, while still keeping the main Ableton window managed. Other rules for plugins etc. have a different class, so their rules were kept as-is. 
This way, all Ableton versions should work. I couldn't find any sub-windows that have Ableton in the title, so this is the best solution I see here for now. 
Tested on Komorebic 0.1.34 with Ableton Live 12.1.5.
=> Add Ignore Rule: All Ableton Sub-Windows

applications.json
PR for  #164 -- sorry for the delay. 
Adds an ignore rule for Photoshop's dialog boxes.
=> Adobe Photoshop PSDiagBox ignore rule

applications.json
When opening a video in VLC from file explorer, the window will resize to fit the content. Depending on your tiling layout, this causes most of VLC to be off-screen or covering other tiles. Anything that updates the window size or position (manually or from komorebi) will snap it back into its tile, but it won't happen automatically.
Adding an `object_name_change` rule fixes this, although it does introduce two small quirks. The first is how long it takes before it snaps into its tile. This can be seen in the After video below. The second is, if you fullscreen the window with komorebi after VLC opens, but before it starts playing the content (this is surprisingly easy to do), you'll fullscreen a blank "VLC (Direct3D11 output)" window which will then persist until it, or VLC, is closed.
I …
=> Add object_name_change rule for VLC

applications.json
VLC's preferences window is named either "Simple Preferences" or "Advanced Preferences" depending on which mode you're in. The current matcher was checking if it was *equal* to "Preferences", which unless there's some secret preferences window I'm unaware of, is never the case.
=> Fix VLC ignore rule missing the preferences window

applications.json
Adds Powertoys File Locksmith and it joins its sibling in being harmoniously ignored for the benefit of us all as it does not play well with Komorebi and starts as a frozen window without this rule in my personal experience.
=> Add: Powertoys - File Locksmith

applications.json
I was maintaining my own changes and occasionally merging in new ones, but now that v0.1.35 added support for multiple app-specific configuration files I can have my more opinionated changes in their own file.
- Add `layered` to other Discord branches
- Realphabetize "Stremio Desktop Community" and "Mod Organizer 2"
- FreeTube
- Grayjay
- Source Engine's Hammer map editor
- HxD
- IDA
- PAYDAY 2
- Unity game windows
- Unreal Engine game and splash windows
- f.lux
- HWiNFO64
- Libre Hardware Monitor
- MacType
- WinCompose
=> Add rules pretaining to games and multiwindow, among other things
